# Generated by Django 4.2.24 on 2026-01-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profileimage/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='blogimage/'),
        ),
    ]
