# Generated by Django 4.2.24 on 2026-01-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_usermodel_profile_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='joined_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
