# Generated by Django 4.2.24 on 2026-01-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_usermodel_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='BLOGID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel'),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='Subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
