# Generated by Django 4.2.24 on 2026-01-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blogmodel_category_blogmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
