# Generated by Django 5.0.6 on 2026-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_blogmodel_is_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
