# Generated by Django 5.0.6 on 2026-01-31 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='blogapp.blogmodel'),
        ),
    ]
